wandb_version: 1

activation:
  value: gelu
augment:
  value: true
batch_norm:
  value: true
batch_size:
  value: 32
dense_layer:
  value: 512
dropout:
  value: 0
epoch:
  value: 1
filter_sizes:
  value:
  - 3
  - 5
  - 5
  - 7
  - 7
learning_rate:
  value: 0.0001
num_filters:
  value:
  - 128
  - 128
  - 64
  - 64
  - 32
optimiser:
  value: adam
weight_decay:
  value: 0
