_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
                - 55
            "2":
                - 1
                - 5
                - 41
                - 53
                - 55
            "3":
                - 2
                - 14
                - 17
                - 23
                - 55
            "4": 3.12.3
            "5": 0.19.8
            "8":
                - 5
            "10":
                - 3
            "12": 0.19.8
            "13": darwin-x86_64
activation:
    value: gelu
augment:
    value: true
batch_norm:
    value: true
batch_size:
    value: 32
dense_layer:
    value: 512
dropout:
    value: 0
epoch:
    value: 1
filter_sizes:
    value:
        - 3
        - 5
        - 5
        - 7
        - 7
learning_rate:
    value: 0.0001
num_filters:
    value:
        - 128
        - 128
        - 64
        - 64
        - 32
optimiser:
    value: adam
weight_decay:
    value: 0
